### ISSUE TITLE
Theme Collection details

### ISSUE THREAD

**Issue by Mister-Hope** [z3by/vuepress-tools#16]
Hi bro, I am the autor of [vuepress-theme-hope](https://www.npmjs.com/package/vuepress-theme-hope) Here is the [repo](https://github.com/vuepress-theme-hope/vuepress-theme-hope/)

It's a monorepo containing a theme and 12 pluigns.

But none of them are collected in to this project. I didnot see PR like this, it seems to be automatic.

So could you please check it out why you are not including it? Or add some supports for monorepo, thanks.

## Additional info

Some really awesome ones:

- [vuepress-theme-hope](https://vuepress-theme-hope.github.io/)
- [vuepress-plugin-md-enhance](https://vuepress-theme-hope.github.io/md-enhance/)
- [vuepress-plugin-photo-swipe](https://vuepress-theme-hope.github.io/photo-swipe/)
- [@mr-hope/vuepress-plugin-copy-code](https://vuepress-theme-hope.github.io/copy-code/)
- [@mr-hope/vuepress-plugin-feed](https://vuepress-theme-hope.github.io/feed/)
- [@mr-hope/vuepress-plugin-reading-time](https://vuepress-theme-hope.github.io/reading-time/)
- [@mr-hope/vuepress-plugin-comment](https://vuepress-theme-hope.github.io/comment/)
- [@mr-hope/vuepress-plugin-pwa](https://vuepress-theme-hope.github.io/pwa/)
- [@mr-hope/vuepress-plugin-seo](https://vuepress-theme-hope.github.io/seo/)
- [@mr-hope/vuepress-plugin-sitemap](https://vuepress-theme-hope.github.io/sitemap/)

Others:

- [vuepress-plugin-add-this](https://vuepress-theme-hope.github.io/add-this/)
- [@mr-hope/vuepress-plugin-git](https://vuepress-theme-hope.github.io/git/)

P.S.:

![image](https://user-images.githubusercontent.com/33315834/118209657-9c4aa400-b49b-11eb-8815-69ab7c57fa53.png)

![image](https://user-images.githubusercontent.com/33315834/118209664-9eacfe00-b49b-11eb-8222-b5a65f7e6e7a.png)

It has a stable download number around 4k/month, times bigger then the first one on the list.

**Comment by z3by** [comment]
Hey @Mister-Hope, Thanks for taking the time to report this issue,
I update the whole site over the weekend and updated how plugins/themes are fetched, you can see the updated website at https://z3by.github.io/vuepress-tools/ and let me know if you find any issues.

**Comment by Mister-Hope** [comment]
Appreciate that👍
